metadata:
  name: frontend
component: frontend
labels:
  appName: frontend
  project_name: expense
selector:
  appName: frontend
  project_name: expense
initContainers:
  enabled: false
containers:
  appVersion: 1.0.3
  name: frontend
schema:
   enabled: false
service:
  type: ClusterIP
ports:
  protocol: TCP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  host: frontend-dev.pdevops78.online